2 components
Fikerte-T/math-magicians2 pull request #2
Opened 2022-01-07 09:03 UTC by Fikerte-T

In this second milestone of the project, I created a Calculator component that displays the UI of the calculator.

2022-01-07 09:30 UTC, elyor-doniyorov requested changes
Hi @Fikerte-T👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![keep-trying-youre-almost-there](https://user-images.githubusercontent.com/67087664/148520959-fd6409f2-d683-4649-b276-19942dc96379.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- To add an app screenshot and valid live demo and license links in your README.md😃

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-07 09:30 UTC, elyor-doniyorov commented on src/App.js
> -import logo from './logo.svg';
- [ ] It would be better if you delete all the boilerplate from CRA (text, images, styles) to make your codebase cleaner. You can find them in `public `and `src` folders in the project directory.

2022-01-07 09:30 UTC, elyor-doniyorov commented on src/App.js
>  function App() {
- [ ] Using the class-based components is one of the main learning purposes of this milestone. Let's make the` App.js` class-based

2022-01-08 04:07 UTC, Fikerte-T commented on src/App.js
>  function App() {
When App.js is made class-based, there is an eslint error "Component should be written as a pure function  react/prefer-stateless-function"

2022-01-08 04:21 UTC, Fikerte-T commented on src/App.js
>  function App() {
So, I got it back to a function-based component.

2022-01-08 04:31 UTC, rukundoeric requested changes
Hi guys, 

_Great job so far 👏 💯 👍. You've done well implementing some of the requested changes. However, there are still some which aren't addressed yet. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 
  - Addressed some of the issues raised from the previous review. 💯 

## Required Changes ♻️
  - [ ] As the previous reviewer mentioned, the project requires that `App` component should be a class-based component on this milestone. And don't worry, you are allowed to use `eslint-ignore` when you have to follow project requirements.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
  
  - N/A 

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-01-08 04:31 UTC, rukundoeric commented on src/App.js
>  function App() {
Hello @Fikerte-T, It is allowed to use `eslint-ignore` while following project requirements.

2022-01-08 04:31 UTC, rukundoeric commented on src/App.js
>  function App() {
Hello @Fikerte-T, It is allowed to use `eslint-ignore` while following project requirements.

2022-01-08 05:49 UTC, arslanbisharat approved these changes
# Approved 👏 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

To Highlight: 
- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error is present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashboard. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2022-01-08 08:22 UTC, merged